config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :comments, only: %i[update destroy]

  scope '/(:locale)', constraints: { locale: /ru|en|sv|cn/ } do
    resources :comments, only: %i[create edit show] do
      post 'check', on: :collection
    end

    namespace :admin do
      resources :comments, only: %i[index show destroy] do
        member do
          post 'toggle', defaults: { format: :json }
          put 'lock', defaults: { format: :json }
          delete 'lock', action: :unlock, defaults: { format: :json }
          put 'approve'
        end
      end
    end

    namespace :my do
      resources :comments, only: :index
    end
  end
end

app/models/biovision/comment/application_record.rb
module Biovision
  module Comment
    class ApplicationRecord < ActiveRecord::Base
      self.abstract_class = true
    end
  end
end

app/models/comment.rb
# frozen_string_literal: true

# Comment
#
# Attributes:
#   agent_id [Agent], optional
#   approved [Boolean]
#   author_email [String], optional
#   author_name [String], optional
#   body [Text]
#   commentable_id [Integer]
#   commentable_type [String]
#   created_at [DateTime]
#   data [JSON]
#   deleted [Boolean]
#   downvote_count [Integer]
#   ip [Inet], optional
#   locked [Boolean]
#   parent_id [Comment], optional
#   spam [Boolean]
#   updated_at [DateTime]
#   upvote_count [Integer]
#   visible [Boolean]
#   vote_result [Integer]
class Comment < ApplicationRecord
  include Checkable
  include HasOwner
  include Toggleable
  include VotableItem if Gem.loaded_specs.key?('biovision-vote')

  AUTHOR_LIMIT = 100
  BODY_LIMIT = 1_048_576

  toggleable :visible

  belongs_to :user, optional: true
  belongs_to :agent, optional: true
  belongs_to :commentable, polymorphic: true, counter_cache: true, touch: false
  belongs_to :parent, class_name: Comment.to_s, optional: true
  has_many :child_comments, class_name: Comment.to_s, foreign_key: :parent_id, dependent: :destroy

  validates_presence_of :body
  validates_length_of :body, maximum: BODY_LIMIT
  validates_length_of :author_name, maximum: AUTHOR_LIMIT
  validates_length_of :author_email, maximum: AUTHOR_LIMIT
  validate :commentable_is_commentable

  after_create { commentable.comment_impact(self) if commentable.respond_to?(:comment_impact) }

  scope :recent, -> { order 'id desc' }
  scope :chronological, -> { order 'id asc' }
  scope :approved, -> { where(approved: true) }
  scope :visible, -> { approved.where(deleted: false, visible: true, spam: false) }
  scope :search, ->(q) { where("to_tsvector('russian', body) @@ phraseto_tsquery('russian', ?)", q.to_s) unless q.blank? }
  scope :list_for_administration, -> { recent }
  scope :list_for_visitors, -> { visible.chronological }
  scope :list_for_visitors_recent, -> { visible.recent }
  scope :list_for_owner, ->(v) { owned_by(v).where(deleted: false).recent }

  # @param [Integer] page
  def self.page_for_administration(page = 1)
    list_for_administration.page(page)
  end

  # @param [Integer] page
  def self.page_for_visitor(page = 1)
    list_for_visitors.page(page)
  end

  # @param [User] user
  # @param [Integer] page
  def self.page_for_owner(user, page = 1)
    list_for_owner(user).page(page)
  end

  def self.entity_parameters
    %i[author_name author_email body]
  end

  def self.creation_parameters
    entity_parameters + %i[commentable_id commentable_type parent_id]
  end

  def self.administrative_parameters
    entity_parameters + %i[deleted visible spam]
  end

  def self.tree(collection)
    result = {}

    collection.each do |entity|
      result[entity.id] = {
        parent_id: entity.parent_id,
        comment: entity,
      }
    end

    result
  end

  # @param [User] user
  def visible_to?(user)
    if commentable.respond_to? :visible_to?
      if deleted?
        UserPrivilege.user_has_privilege?(user, :administrator) && commentable.visible_to?(user)
      else
        commentable.visible_to?(user)
      end
    else
      !deleted? || UserPrivilege.user_has_privilege?(user, :administrator)
    end
  end

  def notify_entry_owner?
    return false unless commentable.respond_to?(:user)

    entry_owner = commentable.user
    return false if entry_owner.nil? || owned_by?(entry_owner)

    !entry_owner.nil?
  end

  def notify_parent_owner?
    return false if parent.nil?

    !parent.owned_by?(user)
  end

  def text_for_link
    "#{self.class.model_name.human} #{id}"
  end

  def commentable_name
    "#{commentable.class.model_name.human} #{commentable_id}"
  end

  def commentable_title
    if commentable.respond_to?(:title!)
      commentable.title!
    elsif commentable.respond_to?(:title)
      commentable.title
    else
      commentable_name
    end
  end

  def profile_name
    user.nil? ? author_name : user.profile_name
  end

  # @param [Integer] word_count
  def preview(word_count = 50)
    words = body.split(/\s+/)
    ellipsis = words.count > word_count ? '…' : ''
    words.first(word_count).join(' ') + ellipsis
  end

  private

  def commentable_is_commentable
    return unless commentable.respond_to?(:commentable_by?)
    return if commentable.commentable_by?(user)

    errors.add(:commentable, I18n.t('activerecord.errors.models.comment.attributes.commentable.not_commentable'))
  end
end

app/controllers/admin/comments_controller.rb
# frozen_string_literal: true

# Administrative handling comments
class Admin::CommentsController < AdminController
  include ToggleableEntity
  include LockableEntity

  before_action :set_entity, except: :index

  # get /admin/comments
  def index
    @collection = Comment.page_for_administration(current_page)
  end

  # get /admin/comments/:id
  def show
  end

  # put /admin/comments/:id/approve
  def approve
    @entity.update(approved: true)
    component_handler.class.notify(@entity)

    head :no_content
  end

  def destroy
    @entity.destroy

    head :no_content
  end

  protected

  def component_class
    Biovision::Components::CommentsComponent
  end

  def restrict_access
    error = 'Managing comments is not allowed'
    handle_http_401(error) unless component_handler.allow?('moderator')
  end

  def set_entity
    @entity = Comment.find_by(id: params[:id])
    handle_http_404('Cannot find comment') if @entity.nil?
  end
end

app/controllers/biovision/comment/application_controller.rb
module Biovision
  module Comment
    class ApplicationController < ActionController::Base
      protect_from_forgery with: :exception
    end
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

# Comments
class CommentsController < ApplicationController
  before_action :restrict_access, except: %i[check create]
  before_action :set_entity, only: %i[edit update destroy]

  layout 'admin', except: :create

  # post /comments/check
  def check
    @entity = Comment.instance_for_check(params[:entity_id], entity_parameters)

    render 'shared/forms/check'
  end

  # post /comments
  def create
    if params.key?(:agree)
      emulate_creation
    else
      create_comment
    end
  end

  # get /comments/:id/edit
  def edit
  end

  # patch /comments/:id
  def update
    if @entity.update entity_parameters
      form_processed_ok(admin_comment_path(id: @entity.id))
    else
      form_processed_with_error(:edit)
    end
  end

  # delete /comments/:id
  def destroy
    if @entity.update deleted: true
      flash[:notice] = t('comments.destroy.success')
    end
    redirect_to(@entity.commentable || admin_comments_path)
  end

  # get /comments/:id
  def show
    redirect_to(admin_comment_path(id: params[:id]))
  end

  private

  def component_class
    Biovision::Components::CommentsComponent
  end

  def restrict_access
    error = 'Managing comments is not allowed'
    handle_http_401(error) unless component_handler.allow?('moderator')
  end

  def emulate_creation
    form_processed_ok(root_path)
  end

  def create_comment
    verify_captcha_and_create
    if @entity.valid?
      unless @entity.approved?
        flash[:notice] = t('comments.create.premoderation')
      end
      next_page = param_from_request(:return_url)
      form_processed_ok(next_page.match?(%r{\A/[^/]}) ? next_page : root_path)
    else
      form_processed_with_error(:new)
    end
  end

  def set_entity
    @entity = Comment.find_by(id: params[:id])
    handle_http_404('Cannot find comment') if @entity.nil?
  end

  def entity_parameters
    params.require(:comment).permit(Comment.entity_parameters)
  end

  def creation_parameters
    permitted = Comment.creation_parameters
    params.require(:comment).permit(permitted).merge(owner_for_entity(true))
  end

  protected

  def verify_captcha_and_create
    entity = Comment.new(creation_parameters)
    verify_recaptcha(model: entity) if component_handler.use_captcha?

    @entity = component_handler.create_comment(entity)
  end
end

app/controllers/my/comments_controller.rb
class My::CommentsController < ApplicationController
  before_action :restrict_anonymous_access

  # get /my/comments
  def index
    @collection = Comment.page_for_owner(current_user, current_page)
  end
end

app/helpers/biovision/comment/application_helper.rb
module Biovision
  module Comment
    module ApplicationHelper
    end
  end
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

# Helper methods for handling comments
module CommentsHelper
  # @param [Comment] entity
  # @param [String] text
  # @param [Hash] options
  def admin_comment_link(entity, text = entity.text_for_link, options = {})
    link_to(text, admin_comment_path(id: entity.id), options)
  end

  # @param [Comment] entity
  # @param [String] text
  # @param [Hash] options
  def comment_link(entity, text = entity.commentable_name, options = {})
    anchor = options.key?(:anchor)
    options.delete(:anchor)
    path = Biovision::Components::CommentsComponent.commentable_path(entity, anchor)
    link_to(text, path, options)
  end
end

app/views/admin/comments/_comment.html.erb
<div class="comment">
  <div class="title">
    <%= comment.commentable.model_name.human %>
    <cite><%= link_to comment.commentable.title, comment.commentable %></cite>
  </div>

  <div class="author">
    <%= user_link comment.user %>
    <%= time_tag comment.created_at %>
  </div>

  <div class="body">
    <%= prepare_comment_text(comment) %>
  </div>

  <div class="footer">
    <ul>
      <li><%= link_to t(:view), comment %></li>
      <li><%= link_to t(:edit), edit_comment_path(comment) %></li>
    </ul>
  </div>
</div>

app/views/admin/comments/_nav_item.html.erb
<div>
  <%= link_to t('.text'), admin_comments_path %>
</div>
<div class="description">
  <%= t('.description') %>
</div>

app/views/admin/comments/index.html.erb
<% content_for :meta_title, t('.title', page: current_page) %>
<% content_for :breadcrumbs do %>
  <%= admin_biovision_component_link(component_handler.component) %>
  <span><%= t('admin.comments.nav_item.text') %></span>
<% end %>

<article class="comments">
  <h1><%= t('.heading') %></h1>

  <ul class="actions">
    <li><%= back_icon(admin_path) %></li>
  </ul>

  <%= paginate @collection %>
  <%= render partial: 'shared/admin/list', locals: { collection: @collection } %>
  <%= paginate @collection %>
</article>

app/views/admin/comments/show.html.erb
<% content_for :meta_title, t('.title', id: @entity.id) %>
<% content_for :breadcrumbs do %>
  <%= admin_biovision_component_link(component_handler.component) %>
  <%= link_to(t('admin.comments.nav_item.text'), admin_comments_path) %>
  <span>
    <%= @entity.id %> (<%= @entity.commentable.model_name.human %>
    <cite><%= @entity.commentable_title %></cite>)
  </span>
<% end %>

<article>
  <h1><%= @entity.commentable_title %></h1>

  <ul class="actions">
    <li><%= back_icon(admin_comments_path) %></li>
    <% unless @entity.deleted? %>
      <li><%= world_icon(Biovision::Components::CommentsComponent.commentable_path(@entity, true)) %></li>
    <% end %>
    <% unless @entity.locked? %>
      <li><%= edit_icon edit_comment_path(id: @entity.id) %></li>
    <% end %>
  </ul>

  <% if @entity.deleted? %>
    <div class="message-box-alert"><%= t(:deleted_entity) %></div>
  <% end %>

  <dl>
    <dt><%= t('activerecord.attributes.comment.user_id') %></dt>
    <dd><%= admin_user_link(@entity.user) %></dd>

    <% unless @entity.author_name.blank? %>
      <dt><%= t('activerecord.attributes.comment.author_name') %></dt>
      <dd><%= @entity.author_name %></dd>
    <% end %>

    <% unless @entity.author_email.blank? %>
      <dt><%= t('activerecord.attributes.comment.author_email') %></dt>
      <dd><%= @entity.author_email %></dd>
    <% end %>

    <dt><%= t('activerecord.attributes.comment.commentable') %></dt>
    <dd><%= comment_link(@entity) %></dd>

    <dt><%= t(:created_at) %></dt>
    <dd><%= time_tag(@entity.created_at) %></dd>

    <dt><%= t('activerecord.attributes.comment.body') %></dt>
    <dd>
      <div class="text">
        <%= simple_format(@entity.body) %>
      </div>
    </dd>
  </dl>

  <%= render partial: 'shared/track', locals: { item: @entity } %>

  <% unless @entity.approved? %>
    <div>
      <button class="js-approve-comment" data-url="<%= approve_admin_comment_path(id: @entity.id) %>"><%= t('admin.comments.entity.in_list.approve') %></button>
      <button class="js-delete-comment" data-url="<%= admin_comment_path(id: @entity.id) %>"><%= t(:delete) %></button>
    </div>
  <% end %>
</article>